### ISSUE TITLE
[Issue]: Mouse malfunction

### ISSUE THREAD

**Issue by sanliang233** [moonlight-stream/moonlight-android#1236] opened 2023-07-28 05:53 UTC
### Describe the bug

The mouse is not working, it feels like the x and y axes are reversed
Device: magic pad 
System: android13

### Steps to reproduce

The mouse is not working, it feels like the x and y axes are reversed
Device: magic pad 
System: android13

### Affected games

all

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

no

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

13

### Device model

 magic pad 

### Server PC OS version

版本	Windows 11 企业版 版本	22H2 安装日期	‎2022-‎09-‎26 操作系统版本	22621.2070 体验	Windows Feature Experience Pack 1000.22659.1000.0

### Server PC GeForce Experience version

3.27.0.112

### Server PC Nvidia GPU driver version

536.67

### Server PC antivirus and firewall software

360

**Comment by cgutman** [comment] 2023-09-02 15:52
Duplicate of #1240

**Closed by cgutman** 2023-09-02 15:52 UTC
Labels: bug
