### ISSUE TITLE
Latency issue on Hisi platform(Harmony TV)

### ISSUE THREAD

**Issue by bluecradle** [moonlight-stream/moonlight-android#928] opened 2021-01-26 09:02 UTC
The latetst moonlight client app v9.8 works in Huawei  Harmony TV.  But the latency performance is not good enough.
Does moonlight support OMX.hisi.video.decoder.hevc ?  It seems hisi hevc decoder is NOT in white list.

Thanks.

**Comment by tranceonline** [comment] 2021-04-19 10:16
Hi, i have a similar issue on my Huawei Mate 10 Pro.
I have a huge average decode time. It's around 40-60 ms all the time. 
Changing settings does not change it. Fps, Mbits, Resolution... nothing.

Tried it on my Galaxy Tab A10, gf's Galaxy S7 and our NVIDIA shield. The Shield is connected via LAN and has decode times around 1-2 ms. The Galaxy Tab and Galaxy S7 have decode times under 10 ms.
Only my Mate 10 Pro has decode times so high :/

Sound comes really delayed and gaming is not good some times.

**Comment by cgutman** [comment] 2021-04-19 14:11
Please try this build on your HiSilicon devices and see if latency improves - https://drive.google.com/file/d/1MXw4O4XmeoKsrPpLNOaVvZg8Wx2_yTVM/view?usp=sharing

**Comment by cgutman** [comment] 2021-04-24 20:08
HiSilicon low latency fix released in v9.8.7.

**Closed by cgutman** 2021-04-24 20:08 UTC

**Comment by tristan-k** [comment] 2021-11-28 22:03
On my quest for a decent 8 inch android moonlight streaming tablet I recently acquired a huawei mediapad m5 8.4 and a samsung galaxy a7 lite. On the mediapad m5 I get a very high decode latency for HEVC (1080p) between 38 - 44ms and on the a7 lite I get a much lower decode for HEVC (1080p) latency between 8 - 12ms. If I force the decoder to H.264 then the latency is even higher between 60 - 85ms on the mediapad m5. I elimnated any network related issued by connecting both tablets via a USB-C to ethernet adapter. I therefore think that the issue isn't fixed. @cgutman Is there a way to improve the latency on HiSilicon (OMX.hisi.video.decoder.hevc)?

**Comment by cgutman** [comment] 2021-11-29 16:34
@tristan-k high decode latency isn't a single issue that can be "fixed". It is a complex hardware-specific problem and may not be solvable without hardware or driver changes in the Android firmware itself.

Moonlight uses the vendor-specific low latency attributes that Huawei suggests per https://developer.huawei.com/consumer/cn/forum/topic/0202325564295980115. We also support the hardware-agnostic low-latency MediaCodec decoding mode introduced in Android 11 (also dependent on device support).

It appears your Mediapad M5 supports neither of those options (as it doesn't meet the requirements mentioned in the Huawei's post nor does it run Android 11). I don't think there's anything we can do.

**Comment by tristan-k** [comment] 2021-11-29 17:22
Thanks for answering. Through Discord I found the [SoC-Benchmark](https://docs.google.com/spreadsheets/d/1WSyOIq9Mn7uTd94PC_LXcFlUi9ceZHhRgk-Yld9rLKc/edit#gid=0) Maybe mention the spreadsheet in the wiki or satement about lower performance of huawei SoCs. Just to give people a heads-up.
