### ISSUE TITLE
Connection terminated issue

### ISSUE THREAD

**Issue by watermelon915** [moonlight-stream/moonlight-android#1032] opened 2022-01-17 03:25 UTC
When i use moonlight connecting my computer,it can be connected,But it will disconnect in three to five seconds.Whether it's public network or LAN

**Comment by watermelon915** [comment] 2022-01-17 03:25
[NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/7878784/NvStreamerCurrent.log)
[NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-android/files/7878785/NvStreamerOld.log)

**Comment by watermelon915** [comment] 2022-01-17 03:26
> [NvStreamerCurrent.log](https://github.com/moonlight-stream/moonlight-android/files/7878784/NvStreamerCurrent.log) [NvStreamerOld.log](https://github.com/moonlight-stream/moonlight-android/files/7878785/NvStreamerOld.log)



This is my log file

**Comment by cgutman** [comment] 2022-02-12 04:41
It looks like the encoder hang issue. Try updating to GeForce Experience 3.25.0.84 and see if that resolves the problem.

**Comment by cgutman** [comment] 2022-05-07 19:43
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

**Closed by cgutman** 2022-05-07 19:43 UTC
