### ISSUE TITLE
RTSP OPTIONS request failed: 11

### ISSUE THREAD

**Issue by jojoguy10** [moonlight-stream/moonlight-android#193] opened 2016-03-30 04:54 UTC
Hello, when I'm trying to stream my Windows 10 computer to my Raspberry Pi 3, i get an error:

$ moonlight stream -app Steam 192.168.11.106
Moonlight Embedded 2.1.4 (EMBEDDED;PI)
Connect to 192.168.11.106...
Stream 1280 x 720, 60 fps, 10000 kbps
Initializing platform...done
Resolving host name...done
Starting RTSP handshake...select() timed out after 10 seconds
RTSP OPTIONS request failed: 11
failed: 11
Error: cannot keep up

Details:
Raspberry Pi 3
Connected over WiFi
Moonlight 2.1.4 Embedded
GeForce Experience 2.11.2.46
GTX 960
Windows 10 64-bit

**Comment by cgutman** [comment] 2016-04-01 15:57
This bug belongs on https://github.com/irtimmer/moonlight-embedded

It looks like a duplicate of https://github.com/irtimmer/moonlight-embedded/issues/340

**Closed by cgutman** 2016-04-01 15:57 UTC
