### ISSUE TITLE
Suggestion: Can Moonlight learn the operating logic of "Nvidia Games" on Shield devices?

### ISSUE THREAD

**Issue by BlessWz** [moonlight-stream/moonlight-android#784] opened 2020-01-25 08:01 UTC
When I press and hold "start", I enter the "mouse and keyboard" state: the right joystick controls the mouse, and “Y” button can turn on the virtual full-function keyboard. Press and hold "start" to exit this mode.

This can solve two problems: 1. The keyboard cannot be turned on on Android TV.
2. The keyboard lacks "Windows", "Ctrl", "Shift" and other keys.

I think the operating logic of the "NVIDIA Game" App is well designed, I hope moonlight can learn from "NVidia game" APP
![NVIDIA 游戏_20191224_151230](https://user-images.githubusercontent.com/30049891/73118203-ff08eb00-3f8b-11ea-8c8e-5252c79ec2ac.png)
![NVIDIA 游戏_20191224_151246](https://user-images.githubusercontent.com/30049891/73118212-23fd5e00-3f8c-11ea-8ce8-24368893dc62.png)

**Comment by cgutman** [comment] 2020-01-26 04:00
Duplicate of #780

**Closed by cgutman** 2020-01-26 04:00 UTC
