### ISSUE TITLE
Streaming black screen！！！

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#485] opened 2017-11-27 04:59 UTC
After testing, as long as the monitor is in the closed state to open the computer, Then streaming will be black screen. Don't turn off the computer, don't disconnect the stream, direct turn on display,The picture will appears on the phone. It means you can only play games at home. Although moonlight supports Internet streaming, you need to keep the monitor on, so it's not good for the monitor

**Comment by cgutman** [comment] 2017-11-27 05:31
Duplicate of https://github.com/moonlight-stream/moonlight-docs/issues/72

**Closed by cgutman** 2017-11-27 05:31 UTC
