### ISSUE TITLE
Can you add mouse touch screen operation mode?

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#687] opened 2019-03-11 08:32 UTC
Can you add a touch operation to a serial computer? I think it's very convenient in many cases. If you need me, I can provide a source code!

**Comment by LiXiaYu** [comment] 2019-03-13 01:47
a native touch operation is necessary to support touch game

**Comment by thw0rted** [comment] 2019-03-13 07:38
Duplicate of #672 (and, incidentally, #674 -- funny how these things come in waves).

**Closed** 2019-03-26 00:35 UTC
