### ISSUE TITLE
[Issue]: Mouse Axis are SWAPED on PHYSICAL mouse

### ISSUE THREAD

**Issue by Trilyan** [moonlight-stream/moonlight-android#1232] opened 2023-07-10 02:54 UTC
### Describe the bug

Having an issue where my physical mouse axis seems to have swapped

- X+ Moves the cursor Y+
- Y+ Moves the cursor X-

Using the touchscreen moves the mouse to the correct axis.

I have tried multiple mice and I get the same result, however trying another Android device on the same computer does not show this issue, pointing to a device-specific problem.

The affected device is a Lenovo Yoga Tab 13 running Android 13. Using a physical mouse outside of Moonlight will have the correct AXIS match the screen orientation, so not sure what is triggering the swap on Moonlight... My hypothesis is that the tablet thinks the screen is in Portrait mode instead of landscape? (even if the image is showing in the correct landscape orientation and the mouse cursor is also correctly drawn) 

### Steps to reproduce

Connect a physical mouse on a Lenovo Yoga Tab 13 and connect to your PC using Moonlight, the axis will be swapped

### Affected games

This happens on all games and also while connecting to Steam

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

Happens with default settings as well

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

13

### Device model

Lenovo Yoga Tab 13

### Server PC OS version

Windows 10 Pro 19094

### Server PC GeForce Experience version

3.27.0.112

### Server PC Nvidia GPU driver version

536.40

### Server PC antivirus and firewall software

Windows Defender and Windows Firewall

**Comment by Chacal1988** [comment] 2023-08-21 18:36
Same problem here. After updating to Android 13 mouse changes direction.
Can't find a solution...

**Comment by cgutman** [comment] 2023-09-02 15:52
Duplicate of #1240

**Closed by cgutman** 2023-09-02 15:52 UTC
Labels: bug
