### ISSUE TITLE
Mouse pointer capture not working with Samsung Dex (Samsung support gave me vague answer)

### ISSUE THREAD

**Issue by NSuknyarov** [moonlight-stream/moonlight-android#573] opened 2018-04-21 16:01 UTC
Mouse pointer capture is not working properly with Samsung Dex (desktop mode for Samsung flagship devices).

My device is Samsung Galaxy S8+ Exynos, the android version is Oreo 8.0 and the build is CRC7.
Moonlight version is 5.7.4

The problem is that the buttons are functioning properly, but you cannot move the pointer/cursor. By pressing a button and dragging you could possibly move it a few pixels, but that's it.

This problem does not occur, when the app is used on the phone. It is working as intended.

Since this problem was mentioned in another issue, I decided to contact Samsung support and after a few weeks of emailing that is the final answer I got on April 10th (I removed the unnecessary bits):

> Thank you for contacting us. We appreciate the opportunity to assist you.
> Kindly know that we have received an answer from the department in charge with Samsung DeX.
> They have investigated this and it seems that this is an issue from the Moonlight application. They will get in contact with the developers of the application and ask them to fix this.
> Also, keep an eye for any up comping updates for that application, since this may solve the issue that you are encountering.

I am not sure what else I can do?

**Comment by cgutman** [comment] 2018-04-21 18:53
Duplicate of #497

**Closed by cgutman** 2018-04-21 18:53 UTC
