### ISSUE TITLE
RTSP Handshake isuee. No error code

### ISSUE THREAD

**Issue by ShawNMusliM** [moonlight-stream/moonlight-android#231] opened 2016-05-19 20:17 UTC
Ok so I finally opened ports and got the app to connect to my desktop. Can see all the games I have added and it will even launch the game for me. But when it goes to the "rstp handshaking" screen it grants a connection error. I tried downloading the APK that you gave two other guys who had this issue but when getting to the pin process it tells me incorrect pin.

failed to send enet packet? Failed to start handshake?

Any help is appreciated.

**Comment by cgutman** [comment] 2016-05-19 22:44
What are the exact messages you see on screen when it fails?

**Comment by ShawNMusliM** [comment] 2016-05-20 00:11
It's says rtsp handshake failed. Unable to send enet. 
On May 19, 2016 6:13 PM, Cameron Gutman <notifications@github.com> wrote:What are the exact messages you see on screen when it fails?

**Comment by Badhoagie91** [comment] 2016-05-21 18:06
I'm having the same issue

**Comment by cgutman** [comment] 2016-05-21 23:23
Closing this as a duplicate of #230

**Closed by cgutman** 2016-05-21 23:23 UTC
