### ISSUE TITLE
Can't sync apps

### ISSUE THREAD

**Issue by aimidin** [moonlight-stream/moonlight-android#124] opened 2015-12-14 19:36 UTC
After pairing my Samsung Galaxy S6 with GeForce Exp.  it starts to refresh my list with games and i have a lot , but after around 30 sec of refreshing it's losing connection with my computer. I tried to reinstall the App from Google play , i even put an beta version of Geforce Exp. , i change the ports , my firewall is not blocking the connection . I don't have any ideas why it's losing connection. And when you try to click on the computer from my device it says  " Send Wake-On-Lan request" and i my PC is not in sleep mode , i try it tho , but no difference .

**Comment by daytron12** [comment] 2015-12-17 20:47
Same issue :(

**Comment by Juzziee** [comment] 2015-12-18 17:04
Hi Aimidin,

I came into the same issue - Try pressing start and typing in "Services" into the windows search. 
Open that up and go down to the Nvidia streaming services and restart those. Should resolve your issue.

You may also need to restart your machine.

**Comment by KevinVording** [comment] 2015-12-22 08:16
I had the same issue, so I reinstalled Geforce Experience and didn't search for any games. I manually added The Witcher 3 to the shield games and tried it again. My phone now instantly picked up The Witcher 3. After searching for games again it went back to "Refreshing apps" and then later losing connection. For me my guess is my Steam.exe is on my C drive and my actual games are installed on my D drive. I'm going to switch all games on my new SSD soon and try again, see what happends.

**Comment by Dayto123beast** [comment] 2015-12-22 18:37
Had this issue. Uninstall geforce experience. Install Version 2.5.11.45. Then everything works again. As a note though set up everything before you close it. Then don't run geforce exp anymore. If you try and run it, it will update and break.

**Comment by evildog1** [comment] 2015-12-24 11:38
Works fine with Geforce experience 2.8.1.21 and i have 6 games installed on E:

**Comment by cgutman** [comment] 2015-12-27 21:06
Can someone still having this issue zip and upload their C:\ProgramData\NVIDIA Corporation \NvStreamSvc folder?

**Comment by KevinVording** [comment] 2015-12-27 22:48
Hopefully you can acces it at this link: https://www.dropbox.com/sh/o9o59cl30k8zq92/AABRsSIQZ5AEm_GEgMvbGSTMa?dl=0

I've reinstalled geforce experience a few times, tried the beta, tried an earlier version. Still as soon as I enter games in the library or the optimization library my steam spot gets overwritten or it will be stuck on refreshing apps.

**Comment by OOPMan** [comment] 2015-12-28 08:46
I am also having this issue. 

I first started having problems with Moonlight after upgrading to GFE 2.8. Following that attempts to view the app list for my system resulted in a message about a timeout connecting to the system running GFE.

I tried upgrading the GFE 2.9 with no luck. I then completely uninstalled GFE and reinstalled GFE 2.8. For a brief moment everything worked again. I connected to my GFE system and a single app was listed, Steam. I was able to open and run Steam with no issues. 

After closing Steam I instructed GFE on my PC to refresh the app list and then once it was done opening the machine in Moonlight again. However, the games list wasn't updated and it still seemed to think the Steam session was running. I used the App settings to clear the cache and data for Moonlight and then proceeded to re-pair with my GFE system. 

At this point, after attempting to refresh Apps for 30 or so seconds it timed out claiming the connection to the PC was lost. 

It seems like GFE 2.8 has introduced a whole raft of issues. I think I may roll back to 2.5 as someone else suggested. Lucky I have an installer lying around as NVidia don't make it very easy to download historical versions.

I have zipped up the NvStreamSrv folder from the Program Files and Program Files (x86) folders. You can find the, here:

https://www.mediafire.com/folder/w4guqxqrdsf21/Nvidia

**Comment by OOPMan** [comment] 2015-12-28 13:15
Slight update. I was able to fix this issue by reverting to GFE 2.5. 

@evildog1 What OS are you running. I wonder if the issue is there?

For the record, I'm running Windows 10 Pro. GFE 2.8 and 2.9 didn't exhibited issues while GFE 2.5 is fine. My GFE detects 57 compatible games.

**Comment by KevinVording** [comment] 2015-12-28 14:19
@OOPMan did 2.5 fix the entire issue and if so do you happen to have a link to download 2.5? Nvidia is making it quite difficult to download older versions.

**Comment by OOPMan** [comment] 2015-12-28 14:47
@KevinVording Reverting to 2.5 fixed the numerous issues I started having after upgrading to 2.8.

Try http://nvidia-geforce-experience.soft32.com/

If that doesn't work, I can upload my 2.5 installer that I have lying around.

**Comment by voltagex** [comment] 2016-01-27 07:58
Is there any longer term fix than reverting to an old version?

**Comment by OOPMan** [comment] 2016-01-27 08:01
@voltagex There are two things you can do:

1: Revert to GFE 2.5
2: Use GFE > 2.5 but do not scan for games. Instead, add manually and make sure you never add more 46.

**Comment by cgutman** [comment] 2016-05-31 03:16
NVIDIA has fixed this in recent GFE versions.

**Closed by cgutman** 2016-05-31 03:16 UTC

**Comment by aimidin** [comment] 2016-05-31 10:52
thank you for letting me know :)

2016-05-31 5:16 GMT+02:00 Cameron Gutman <notifications@github.com>:
