### ISSUE TITLE
Mouse capture not working in DeX (Oreo)

### ISSUE THREAD

**Issue by Tyler277** [moonlight-stream/moonlight-android#497] opened 2017-12-22 05:57 UTC
So I have the S8+ on oreo beta 3, when using moonlight it works as normal when opened, device mouse moving and the streamed mouse following poorly. Once I hit the keys to enable mouse capture, my mouse then vanishes, and the mouse in the stream does not move, or sometimes vanishes. When using a USB mouse, the mouse in stream will lock to the upperleft corner and will let me drag it out but then jumps back to the corner, almost as if im in a game and the system thinks the corner is the center. 
Is this a bug in moonlight or the oreo beta? So far it seems like every other feature works perfectly, only the mouse is an issue

**Comment by cgutman** [comment] 2017-12-22 06:23
Mouse capture is enabled by default - it shouldn't require you to press Ctrl+Shift+Z to capture. That said, Ctrl+Shift+Z does toggle mouse capture properly with Oreo mouse capture. You should be able to see it toggling between displaying the Android cursor and controlling the Windows cursor if you press that combo a few times.

As luck would have it, I also have an S8 running Oreo Beta 3. I tried a USB mouse and keyboard and toggled capture with Ctrl+Shift+Z and even messed with multi-window too and it all seems to work correctly for me.

**Comment by Tyler277** [comment] 2017-12-22 06:31
huh, it still works the same as on nougat, double mouse and when the keys are pressed it makes it worse. Even attempted to reinstall the app and nothing. Attempted it on the offical dex dock with 2 different USB mice and on the elite x3 lapdock and nuthin. Reinstalled the app and attempted the root version just because, still the same result. Which firmware are you on? Im on ZQZQ the the december security patch, are you on a dex setup or just using an otg cable or bluetooth mouse?

**Comment by cgutman** [comment] 2017-12-22 06:41
My S8 is running OPR1.170623.032.G950USQU2ZQL8 (December security patch). I'm just using a USB mouse without DeX. Does it work for you outside of DeX?

**Comment by Tyler277** [comment] 2017-12-22 06:48
Yep thats it, switched over to screen mirror and it works, a little laggy but that could be my setup, but it does work without dex. So, since it seems to just be an issue inside of dex, is that something that could be implemented at some point?

**Comment by cgutman** [comment] 2017-12-22 07:24
Moonlight uses the standard Android Oreo API to request pointer capture. If the OS decides that it won't allow it, there's not much I can do. You can leave beta feedback saying that Oreo pointer capture isn't working in DeX mode.

Can you somehow full-screen Moonlight and see if it works in DeX that way? It's possible that they've intentionally disabled pointer capture in windowed DeX mode to prevent a window from stealing the cursor and having no way to get it back.

**Comment by Tyler277** [comment] 2017-12-22 07:29
I guess that's the point of a beta, I can do that. Well, I did disable the option to draw over other apps, ran in full screen, used a USB mouse and it attempted to capture it, it was no longer pulling the system mouse, but the mouse in moonlight was still locked to the corner. I could use right and left click and drag the windows if I really shook the mouse, but as soon as I let go it shoots to the top left corner and stays there. Is that still an issue under the beta or dex?

**Comment by cgutman** [comment] 2017-12-22 07:46
Does the mouse only get stuck in the corner when capture is enabled? If you toggle capture off with Ctrl+Shift+Z does the mouse work normally (obviously not controlling the PC anymore)?

**Comment by Tyler277** [comment] 2017-12-22 08:09
Only in capture, when I disable it, it goes back to performing like previous versions where it follows the system mouse

**Comment by cgutman** [comment] 2017-12-23 03:32
Ok, sounds like a bug in mouse capture in DeX mode then. I'd go ahead and report it to Samsung if you haven't already.

**Comment by NSuknyarov** [comment] 2018-02-27 15:04
I have the same problem. I am using Samsung S8+ with the latest release of Android Oreo.

In DeX mode the mouse capture doesn't work. The pointer is not moving, but left and right mouse clicks work. Outside of DeX mode everything is as it should.

**Comment by dennore** [comment] 2018-03-01 09:11
Hey all,

i have a strange mouse move behaviour on my samsung s8 with the new android oreo update.
the new oreo feature which hides the local android cursor is great, BUT:
when i move my mouse very slow, the movement will not get to the remote computer. only when i move the mouse faster it works.

but if i press ctrl+shift+z i see the android mouse moving precise even if i do slow movements.
also tried a different usb mouse

this makes playing a shooter impossible, cause you cannot aim :(

anyone else have the same issue?

regards
dennore

**Comment by subjectdenied** [comment] 2018-03-21 01:59
same here, note8 oreo - just flashed my phone to get oreo mouse capturing on moonlight. samsung for me now is the joke in the smartphone industry, first it takes them half a year to get oreo out of the door for flagship models, and then they cannot even get a feature working correctly, that should have been already in their nougat stock rom when taking into account they sell dex as desktop replacement ... and yes it is a bug, that is known for months already, specific to samsung devices, according to a post in reddit

**Comment by cgutman** [comment] 2018-04-21 18:58
Samsung got in touch with me about the DeX issues. I got a DeX unit that I was able to reproduce the issues with. I'm going to try to debug it today.

**Comment by Tyler277** [comment] 2018-04-21 20:59
Dude that's awesome, let me know if there's anything I can do to help. Did they happen to say if it was a DeX bug?

**Comment by cgutman** [comment] 2018-04-22 01:01
I did some debugging and it appears to me to be a bug in DeX itself. I sent them a test APK that uses pointer capture. It works properly in screen mirroring but is broken in DeX mode (same symptoms as Moonlight).

Hopefully they can figure out the what's wrong and potentially provide a workaround. I'll keep this ticket updated with their response.

**Comment by Hobb** [comment] 2018-05-29 20:43
Any news on this topic?

**Comment by cgutman** [comment] 2018-05-29 20:54
Samsung confirmed that it's an issue with the pointer capture API in DeX. They are working on fixing it. Not sure whether it will require an OS update or if the software can be updated via the app store.

**Comment by Tyler277** [comment] 2018-07-04 05:08
any update from samsung? The DeX app clearly hasnt been updated, the steam link beta doesnt work with mouse capture either. Kinda sucks

**Comment by NSuknyarov** [comment] 2018-07-04 08:21
Samsung updates Dex with the system updates, that come out every month. Unfortunately, for the last 3 months at least, there were no DeX updates (this is the case for my exynos S8+). So nobody outside Samsung knows when they will release the fix. The good thing, I guess, is that they know there is a problem with their software and they have to fix it at some point.

The Steam Link app is not bad, it is not up to the level of Moonlight, but it has the advantage of not requiring Nvidia hardware.

**Comment by NSuknyarov** [comment] 2018-08-26 05:55
I got my Note 9 two days ago, it is the Exynos/European version. DeX is at v.2.6.63 
I was able to play CS:GO with mouse&keyboard and navigate my desktop in DeX mode, so it looks like they fixed the problem.
Unfortunately my S8+ is still not getting any DeX updates.

**Comment by cgutman** [comment] 2020-04-18 07:10
Relative mode is fixed on Samsung's Android Pie firmware. Absolute mode is now supported for earlier OSes with https://github.com/moonlight-stream/moonlight-android/commit/c3b81554f43301a7e37a1d6bf743df9ff3f3ae0f

Closing this as fixed.

**Closed by cgutman** 2020-04-18 07:10 UTC
Labels: bug
