### ISSUE TITLE
Duplicate Games Listed - After Hiding in GFE

### ISSUE THREAD

**Issue by chriseich21** [moonlight-stream/moonlight-android#731] opened 2019-08-20 18:25 UTC
Moonlight V8.1 and GFE V3.20.0.105

So I added paths to my entire C, D, and E drives, after removing individual program files and program files (x84) paths for each drive as games that are shown as game stream ready are not showing up (Vermintide 2, Metro Exodus, others). This caused about 20 duplicates that I noticed when I went to stream in Moonlight (they're not because I have a manual shortcut). The same occurred in GFE and I hid them all, however they are still listed in Moonlight and there is no option to hide/delete individual shortcuts in the app.

**Comment by cgutman** [comment] 2019-08-21 02:22
We don't control the list of games Nvidia sends to us. There's no "hidden" attribute or similar. We just display whatever we get.

The request to manually hide games is a duplicate of #651

**Closed by cgutman** 2019-08-21 02:22 UTC
