### ISSUE TITLE
Right click on touch screen issue

### ISSUE THREAD

**Issue by zycboss** [moonlight-stream/moonlight-android#990] opened 2021-06-23 04:49 UTC
In the [guide](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-Options) it sais "Hold one finger down and tap a second finger to right-click."

But in real world, you have to make a double-tap, hold, then release for right click, this will shift the first tap position and make control less accurate, please fix it.

**Device details**
 - Android version: Android 10
 - Device model: Huawei P30

**Server PC details**
 - OS: Windows 10 21H1
 - GeForce Experience version:  3.23.0.74
 - Nvidia GPU driver: 466.77
 - Antivirus and firewall software: NO
 
**Additional context**
Enable/disable back and forward mouse button option dose not make any differce on this issue.

**Comment by cgutman** [comment] 2021-06-25 05:48
I'm not sure what you mean by "in the real world, you have to make a double-tap, hold, then release for right click".

You definitely don't need to do that. You touch the screen with one finger, then without lifting that finger, tap the screen with your second finger.

It's _possible_ you were affected by the bug fixed in 86ee30e9b4da4b1a812831bc012ce2f943b73777 but that seems unlikely given that double-tapping would not affect that issue in any way (and holding might actually trigger it).

Below is the raw logs of those actions with the resulting right click from my Galaxy Note 9:
```
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_DOWN, actionButton=0, id[0]=0, x[0]=2175.918, y[0]=1120.0781, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=39049119, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2175.918, y[0]=1119.7266, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=39049202, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2176.6406, y[0]=1118.6719, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2000000, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=39049286, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_POINTER_DOWN(1), actionButton=0, id[0]=0, x[0]=2176.6406, y[0]=1118.6719, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2680.332, y[1]=805.0781, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=2, historySize=0, eventTime=39049294, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2178.086, y[0]=1117.6172, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2680.332, y[1]=804.77313, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=2, historySize=1, eventTime=39049325, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2178.086, y[0]=1117.6172, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2680.332, y[1]=804.72656, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=2, historySize=1, eventTime=39049336, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2178.8086, y[0]=1116.5625, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2680.332, y[1]=804.72656, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=2, historySize=1, eventTime=39049352, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2178.8086, y[0]=1116.5625, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2681.0547, y[1]=803.6719, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2000000, edgeFlags=0x0, pointerCount=2, historySize=0, eventTime=39049361, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_POINTER_UP(1), actionButton=0, id[0]=0, x[0]=2178.8086, y[0]=1116.5625, toolType[0]=TOOL_TYPE_FINGER, id[1]=1, x[1]=2681.0547, y[1]=803.6719, toolType[1]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=2, historySize=0, eventTime=39049369, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Right mouse button down
I/com.limelight.LimeLog: Right mouse button up
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=2179.5312, y[0]=1115.5078, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x2000000, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=39049386, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
I/com.limelight.LimeLog: Raw touch event: MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=2179.5312, y[0]=1115.5078, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=39049394, downTime=39049119, deviceId=2, source=0x1002, displayId=0 }
```

**Comment by zycboss** [comment] 2021-06-25 13:39
I didn't see a release of v9.9.6, so I cannot try if this has fixed in this version. I have shot a video to show what problem I ran into.

FYI, other gestures like scrolling and pop keyboard are working fine, so its shouldn't be a multi-touching problem on my device

https://user-images.githubusercontent.com/29044143/123433147-b7154a00-d5fd-11eb-99cd-bf9eebe91e2a.mp4

.

**Comment by cgutman** [comment] 2021-06-25 15:17
Oh, that's because you're in touchscreen mode and you're trying to use gesture for trackpad mode. So this is working as intended, though we should update the docs to indicate the different set of gestures for both modes.

In touchscreen mode, right-click is a long press like on Windows touchscreen PCs.

**Comment by zycboss** [comment] 2021-06-25 16:20
OK, I never use Windows PCs with touchscreen though, I thought the right-click logic should be same as trackpad, so, quite confusing.

So yeah, maybe update the guide is helpful to other new users like me, I have seen a lot of people asking this same question on discord these days.

**Comment by cgutman** [comment] 2021-06-25 22:48
Ok, I've updated the documentation on https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#keyboardmousegamepad-input-options

I think everything is solved now, so closing this issue.

**Closed by cgutman** 2021-06-25 22:48 UTC
