### ISSUE TITLE
Moonlight app won't find PC anymore

### ISSUE THREAD

**Issue by ElSturge** [moonlight-stream/moonlight-android#474] opened 2017-11-10 00:47 UTC
I set up Moonlight about 3 weeks ago and everything was working perfectly. About 3 days ago i was able to stream games to my phone no problem. But today it just wont work. Everything is updated, I haven't changed settings on either device, it just fails to find my PC now. 
Any ideas?

**Comment by cgutman** [comment] 2017-11-10 08:52
If you open the GeForce Experience settings page, does the Shield tab show up? People have reported that disappearing after the last GFE update. If it's still there, is GameStream still enabled?

Can you reach http://127.0.0.1:47989/serverinfo on your GFE PC?

**Comment by ElSturge** [comment] 2017-11-10 10:25
Yes, everything such as the shield section of GFE is still there, i even reinstalled GFE but still nothing. I've tried all i can think of at this rate

**Comment by ElSturge** [comment] 2017-11-10 10:57
I tried connecting via IP. Uninstall and reinstall GFE, reinstall Moonlight, clearing data for the app. Connect via Local WiFi and over the Internet using port forwarding, and neither work. I've allowed GFE through the Firewall, made sure Windows is up to date, everything I can think of. I have no interfering applications installed, I'm extremely stumped, as it was working via Local WiFi and over the Internet just a few days ago.

**Comment by Slayer418** [comment] 2017-11-10 11:13
Same issue here, it's really weird, it was working and now it isn't while nothing changed, no GFE update or anything.

**Comment by ElSturge** [comment] 2017-11-10 11:15
Thought it was just me, at least I'm not the only person having problems

**Comment by Slayer418** [comment] 2017-11-10 11:17
Here is my Tablet trying to communicate
https://i.imgur.com/Wu2Kbp9.jpg
https://i.imgur.com/zLDllBK.jpg

and http://127.0.0.1:47989/serverinfo leads to a white page.

**Comment by ElSturge** [comment] 2017-11-10 11:27
I have been able to access http://127.0.0.1:47989/serverinfo , it shows me all the code and as far as i can see, everything is successful.

**Comment by ElSturge** [comment] 2017-11-10 15:15
Anyone have any other ideas or suggestions as I'm really stumped? Even disabling the Firewall completely doesn't help.

**Comment by Slayer418** [comment] 2017-11-10 19:42
nssCurrent.log last line, keeping to repeat over and over 

`#4(D)[2017-11-10 19:33:31,336]=14:33:31={00002468}<Mongoose>         Accepted socket 2092
#5(D)[2017-11-10 19:33:31,336]=14:33:31={00002468}<Mongoose>         queued socket 2092
#6(D)[2017-11-10 19:33:31,336]=14:33:31={00002680}<Mongoose>         grabbed socket 2092, going busy
#7(D)[2017-11-10 19:33:31,336]=14:33:31={00002680}<Mongoose>         going idle
#8(D)[2017-11-10 19:33:31,344]=14:33:31={00002468}<Mongoose>         Accepted socket 2092
#9(D)[2017-11-10 19:33:31,344]=14:33:31={00002468}<Mongoose>         queued socket 2092
#0(D)[2017-11-10 19:33:31,344]=14:33:31={00000D4C}<Mongoose>         grabbed socket 2092, going busy
#1(D)[2017-11-10 19:33:31,345]=14:33:31={00000D4C}<Mongoose>         going idle
#2(D)[2017-11-10 19:33:31,362]=14:33:31={00002468}<Mongoose>         Accepted socket 2092
#3(D)[2017-11-10 19:33:31,362]=14:33:31={00002468}<Mongoose>         queued socket 2092
#4(D)[2017-11-10 19:33:31,362]=14:33:31={00000AA8}<Mongoose>         grabbed socket 2092, going busy
#5(D)[2017-11-10 19:33:31,412]=14:33:31={00000AA8}<OpenSSLCertUtils> OpenSSLCertUtils::VerifyCallback: num:18, self signed certificate, depth: 0, /CN=NVIDIA GameStream Client
#6(D)[2017-11-10 19:33:31,412]=14:33:31={00000AA8}<OpenSSLCertUtils> OpenSSLCertUtils::VerifyCallback: No errors
#7(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<Mongoose>         /serverinfo
#8(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<MongooseMongoose> MongooseHttpServerInternal::InvokeHandler: ssl = 00000000078F5700
#9(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<OpenSSLCertUtils> OpenSSLCertUtils::GetPeerCertificate is called. ssl: 00000000078F5700
#0(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<MongooseMongoose> ClientCert retrieved in SSL handshake
#1(W)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<NetworkStreamSer> Server is offline, returning service unavailable error
#2(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<MongooseMongoose> Successfully sent the response back the the client.
#3(D)[2017-11-10 19:33:31,428]=14:33:31={00000AA8}<Mongoose>         going idle
#4(D)[2017-11-10 19:38:03,868]=14:38:03={00002468}<Mongoose>         Accepted socket 2092
#5(D)[2017-11-10 19:38:03,868]=14:38:03={00002468}<Mongoose>         queued socket 2092
#6(D)[2017-11-10 19:38:03,868]=14:38:03={000006B4}<Mongoose>         grabbed socket 2092, going busy
#7(D)[2017-11-10 19:38:03,868]=14:38:03={000006B4}<Mongoose>         /serverinfo
#8(D)[2017-11-10 19:38:03,868]=14:38:03={000006B4}<MongooseMongoose> MongooseHttpServerInternal::InvokeHandler: ssl = 0000000000000000
#9(W)[2017-11-10 19:38:03,868]=14:38:03={000006B4}<NetworkStreamSer> Server is offline, returning service unavailable error
#0(D)[2017-11-10 19:38:03,869]=14:38:03={000006B4}<MongooseMongoose> Successfully sent the response back the the client.
#1(D)[2017-11-10 19:38:03,869]=14:38:03={000006B4}<Mongoose>         going idle
`

**Comment by Slayer418** [comment] 2017-11-10 20:55
Well here are all my logs : 
Here are my logs :


SSASCurrent - https://pastebin.com/JJqFBW8g

nvstreamsvcCurrent - https://pastebin.com/gM6q9myF

NvcSSAU - https://pastebin.com/ttRK93vg

nssCurrent - https://pastebin.com/LMtZ3kGh

GsTelemetryCurrent - https://pastebin.com/DMgiqtfN

**Comment by Slayer418** [comment] 2017-11-11 10:53
Ok I've finally tried to uninstall GFE completely and reinstall it and... it worked, PC detected again, streaming works. No idea what happened but Gamestream got corrupted I guess.

**Comment by ElSturge** [comment] 2017-11-11 12:09
Glad you've got it working. I tried that last night but it keeps failing to install. My resolution is now all wrong again. Any idea why? Could there be some leftover files or processes that's preventing any drivers from installing?

**Comment by Slayer418** [comment] 2017-11-11 17:34
Maybe, try with http://www.guru3d.com/content-page/guru3d-driver-sweeper.html. I didn't need to do tho.

**Comment by ElSturge** [comment] 2017-11-11 21:45
Uninstalled GFE and finally managed to install it again along with the newer drivers. Updated the Moonlight app and still nothing. 
I've since rebooted my router, enabled DMZ in the router settings. 
Really stuck now

**Comment by cgutman** [comment] 2017-11-18 01:38
Duplicate of #476

**Closed by cgutman** 2017-11-18 01:38 UTC
