### ISSUE TITLE
Virtual controller rocker out of control

### ISSUE THREAD

**Issue by 8116453** [moonlight-stream/moonlight-android#671] opened 2019-02-05 05:26 UTC
Hello! I'm sorry to disturb you. The left and right rockers of the virtual controller are out of control. When you press the rocker to move, it still works when you release the rocker. The result is that the characters move forward. Could you fix this problem, please?
How to adjust the dead zone of the rocker of the virtual controller?

**Comment by cgutman** [comment] 2019-02-06 06:56
Duplicate of #663

Please do not file multiple issues for the same problem.

**Closed by cgutman** 2019-02-06 06:56 UTC
