### ISSUE TITLE
Right Click from mouse not sending on android

### ISSUE THREAD

**Issue by Alec123445** [moonlight-stream/moonlight-android#568] opened 2018-04-12 22:38 UTC
I have a otg connector and a mouse plugged into it. Right clicks work in android. But it does not go through moonlight. I am on android 8.0 so it should work, but it is not.

**Comment by samgalactic2** [comment] 2018-04-13 05:44
What mouse is it? My left and right mouse buttons work, scrollwheel works, but clicking the extra buttons on the side do nothing.

**Comment by Alec123445** [comment] 2018-04-13 06:01
Logitech g900. I've tried other mice and hasn't worked. Navigating android the right click acts as the back button. I have a oneplus 5t. maybe they've tweaked the mouse in oreo. I'm going to root my android tomorrow and use rooted moonlight and see if that fixes it.

**Comment by cgutman** [comment] 2018-06-16 22:59
Duplicate of #424 which is fixed

**Closed by cgutman** 2018-06-16 22:59 UTC
