### ISSUE TITLE
Please add a way to close the session with the remote

### ISSUE THREAD

**Issue by Michoko92** [moonlight-stream/moonlight-android#787] opened 2020-01-30 22:02 UTC
Hi,
I have a Shield TV, but I don't use the NVidia gamepad: since my PC is close enough, I can use my wireless Xbox 360 gamepad directly connected to my PC. It reduces latency, and allows me to have only one wireless receiver plugged to my PC (so I can play on the Shield or on my PC indifferently).

So it would be nice if there was a hotkey that would allow to quit the Gamestream using the remote (like for example a long press on the OK button). Thank you for this amazing app! (it saved my life quite a few times when Nvidia did poor UI choices with their official Nvidia Games app)

**Comment by cgutman** [comment] 2020-02-27 03:23
This seems like a duplicate of #788. The back button normally serves the purpose of disconnecting from the stream.

**Closed by cgutman** 2020-02-27 03:23 UTC

**Comment by Michoko92** [comment] 2020-02-27 17:29
Well, it was not exactly the same idea. I was suggesting to have a direct way of ending a gamestream session while playing, like what we do with a long press on the start button of the shield controller. It would be handier than having to go back to the games grid,  selecting the currently active session, go down to the right menu item, and then confirm we want to end the session.
