### ISSUE TITLE
Empty game tiles

### ISSUE THREAD

**Issue by qualityghost** [moonlight-stream/moonlight-android#340] opened 2017-02-12 15:45 UTC
I've installed the latest version of the Moonlight on my Android TV which is Philips 55PUS6501/12 and game streaming works fine but when I go to main view with games then all game tiles are grey without graphic. Empty tiles are displayed only for scanned games. For manually added games selected graphic is displayed correctly. Stem tile is displayed fine also. On the computer is installed GFE version 3.3.0.95.

**Comment by cgutman** [comment] 2017-02-12 21:45
Duplicate of https://github.com/moonlight-stream/moonlight-android/issues/335

**Closed by cgutman** 2017-02-12 21:45 UTC
