### ISSUE TITLE
PC not paired

### ISSUE THREAD

**Issue by nayrazag** [moonlight-stream/moonlight-android#1025] opened 2021-12-28 14:17 UTC
Hello. I can't pair any android phone devices to moonlight other than my main phone (Pixel 3A XL). I tried Moto G play 2021, Pixel 1, Essential phone but no luck. All the phones see the PC and I get the prompt to enter pin on my host PC (Nvidia 1080ti) but after I enter PIN and phone goes to refreshing app list stage within a second it exits out back to host PC list with message "PC not paired". I can still try to re connect and enter pin again bot the same problem appears after I enter it. I installed moonlight internet streaming tools and everything works there but no luck pairing phones.
On main phone everything works as it should.
Pixel 3a xl - Android 12 - works
Pixel 1 - Android 10 - not working
Essential phone - Android 10 - not working
Moto g play 2021 - Android 11 - not working
Host PC - windows 10 21h2 works with any PC client streaming one only one phone - pixel 3a xl, but not any other phone

**Comment by cgutman** [comment] 2021-12-28 23:32
I can't reproduce that issue here on Win10 21H2 and GFE 3.24.0.126 (latest as of today).

What version of GeForce Experience is your PC running?

Are you pairing over your home network or over the Internet?

**Comment by nayrazag** [comment] 2021-12-29 02:49
I use the latest version of GFE (like yours). I recorded screen of my phone to reproduce what happens.
https://imgur.com/a/lvUGUJZ
gigabyte pc works jut fine but asrock keeps giving me a problem.

**Comment by HildaM** [comment] 2022-02-13 00:58
I have the same problem, too!
The version I used for PC and Android is the latest. But I still can't connect.
I tried to turn off the firewall, but it didn't work.
Device:
- PC: win10 21H2
- Android: Harmony OS 2.0 Huawei MatePad 11

**Comment by cgutman** [comment] 2022-02-13 01:31
This was fixed in GeForce Experience 3.25.0.84

> Fixed an issue with Gamestream with pin pairing.

https://www.nvidia.com/en-us/geforce/geforce-experience/download/

**Closed by cgutman** 2022-02-13 01:31 UTC

**Comment by shudack** [comment] 2022-06-25 15:09
> I use the latest version of GFE (like yours). I recorded screen of my phone to reproduce what happens. gigabyte pc works jut fine but asrock keeps giving me a problem. https://imgur.com/a/f4oW2vK
> 
> I'm sorry I sent the wrong link, I updated it to cerrect one. Thank you
> 
> I'm pairing over home network and I also installed moonlight internet hosting tool so it's visible on both home network and internet.

I have the same problem.. After I typed the pin, it said that the "PC not paired". I tried in Nvidia Shield Pro and Galaxy S9+ without success.
GeForce Experience: 3.25.1.27
PC: Win10 21H2
Android 11: Nvidia Shield Pro
Android 10: Galaxy S9+

Do you have any problems with this GeForce version?

**Comment by HildaM** [comment] 2022-06-25 15:38
My Computer GeForce Experience version is 3.24.0.135, but my pad is the latest one.
I used to have the 'PC not paired' problem but now I don't.
It might be related to the version of the software,  or not.
You can try to install a old version of GeForce Experience, it might be help, but I am not guarantee for that, because I can't figure out the core reason of this bug.

My system is Win10 21H1.
Android device is HUAWEI Matepad11.



| |
Quan
***@***.***
|




---- Replied Message ----
| From | Flávio ***@***.***> |
| Date | 06/25/2022 23:10 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [moonlight-stream/moonlight-android] PC not paired (Issue #1025) |

I use the latest version of GFE (like yours). I recorded screen of my phone to reproduce what happens. gigabyte pc works jut fine but asrock keeps giving me a problem. https://imgur.com/a/f4oW2vK

I'm sorry I sent the wrong link, I updated it to cerrect one. Thank you

I'm pairing over home network and I also installed moonlight internet hosting tool so it's visible on both home network and internet.

I have the same problem.. After I typed the pin, it said that the "PC not paired". I tried in Nvidia Shield Pro and Galaxy S9+ without success.
GeForce Experience: 3.25.1.27
PC: Win10 21H2
Android 11: Nvidia Shield Pro
Android 10: Galaxy S9+

Do you have any problems with this GeForce version?
