### ISSUE TITLE
Moonlight always streams in H.264 with RTX 3080 host GPU

### ISSUE THREAD

**Issue by RoelVG** [moonlight-stream/moonlight-android#884] opened 2020-10-01 20:51 UTC
I recently upgraded my host GPU from a 980ti to a 3080. On the 980ti I was able to enforce H.265/HEVC encoding when using the "Always use H.265 (may crash)". I still tested this a few weeks ago.
Now I replaced the 980ti with a 3080, and suddenly it's impossible to stream using H.265. Even when using the "Always use H.265 (may crash)" option, it will still use H.264 without showing any sort of error or warning. I am experiencing this both when using Moonlight on a Shield TV Pro (2019) and on my phone.

Any suggestions? Or is this an issue on Nvidia's side? Find it especially weird since the 3080's NVENC should have gotten much better at HEVC compared to the 980ti, so I expected it to even use that by default.

**Comment by cgutman** [comment] 2020-10-01 20:54
Duplicate of https://github.com/moonlight-stream/moonlight-qt/issues/447

**Closed by cgutman** 2020-10-01 20:54 UTC
