### ISSUE TITLE
Moonlight freeze on NVIDIA Shield 2019

### ISSUE THREAD

**Issue by nattyduber** [moonlight-stream/moonlight-android#1040] opened 2022-02-03 10:55 UTC
I'm on latest version of GeForce expérience and on Android TV 11 on Shield 2019
Thèse days i played god of War 2018 and ff7 remake intergrade
Sometime , screen freeze, unplayable. Need to restart Moonlight
When the screen freezing, music is Always ok and i Can listen Kratos speak for example

Why its freezing?
Thanks

**Comment by nattyduber** [comment] 2022-02-03 15:45
Same problem on Moonlight Windows 11 (surface pro 7) and Xiaomi redmi 9 (miui12.5)

Before, all was ok..

**Comment by nattyduber** [comment] 2022-02-03 15:45
And 4g or wifi its the same..

**Comment by cgutman** [comment] 2022-02-04 02:20
On your host PC, disable the hardware-accelerate GPU scheduling option in your Graphics Settings.

**Comment by nattyduber** [comment] 2022-02-04 06:39
Cgutman : do you know how?
I have a gtx1080 on win11

Thanks

**Comment by nattyduber** [comment] 2022-02-04 07:39
Oh i think i'have found how disable it.
Thanks i will try this night :)

**Comment by nattyduber** [comment] 2022-02-04 19:55
Hey , test failed. Same problem with or without hardware-accelerated GPU scheduling option...

**Comment by cgutman** [comment] 2022-02-12 04:40
Try updating to GeForce Experience 3.25.0.84 and see if that resolves the problem.

**Comment by panic2k** [comment] 2022-02-18 17:21
I have the same issue with newest Gameready Drivers from 14th and GeForce Experience 3.25.0.84 on Android and Linux Client. I didn't tryed Windows but i expect same behavior.

**Comment by leni8ec** [comment] 2022-03-09 19:20
Have a same problem on my Shield 2019 TV PRO (Android 11)

**Comment by YABIJIU** [comment] 2022-05-03 01:10
> On your host PC, disable the hardware-accelerated GPU scheduling option in your Graphics Settings.

it doesn't work.and it influences the Vibration of controler.recover the vibration must reset PC

**Comment by darksidemilk** [comment] 2022-05-05 05:44
I'm on windows 11, rtx 3080ti. Playing on android over wifi 6 and the host is on a 2.5 gbe lan connection (so over 1 gbps link on client and server). This issue was driving me nuts and kept getting worse. I couldn't even get past the main menu of some games. I gave the gpu scheduling turn off a try. I also disabled the windowed optimizations and auto hdr that were on the same setting screen. Restarted the computer and gave streaming another go. It worked perfectly again. I only played for a few minutes, and it sometimes in the past would freeze after maybe 10-20 minutes or it would freeze every 30 seconds. For sure past the every 30 seconds problem. Thank you for the fix. There's more to test that used to work for me on windows 10 like different monitors and streaming with the monitor off. But very happy that this simple change helped this much, thanks @cgutman!

**Comment by YABIJIU** [comment] 2022-05-05 05:57
> 

桌面按右键属性， 进入显示设置 ，找到图形设置进入，找到硬件加速gpu计划，关闭就行了。

我周日试了一天，没有出现冻结画面，就是偶尔会掉网速，但是已经基本正常了。你win11的这个项目我也不知道在哪，我这是win10的，你参考一下。如果不行，还有个办法，显卡驱动退回472.11，我们中国有人已经亲测这个方式有用，不过moonlight更新10版本之后，就不用了这么做了。

**Comment by cgutman** [comment] 2022-05-07 19:42
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

**Closed by cgutman** 2022-05-07 19:42 UTC
