### ISSUE TITLE
Moonlight does not support the joystick control of UWP games

### ISSUE THREAD

**Issue by shinobiz** [moonlight-stream/moonlight-android#483] opened 2017-11-27 04:47 UTC
I am Chinese, please forgive my English is not very good

I've found a way to support UWP joystick control by streaming

A streaming software from China can simulate the XBOX 360 controller well under the horizon 3, and LT/RT has linear control

But I don't understand the program. The moderator can download it and study it http://www.ihuaj.com/gamecc/

But in addition to the success of simulating XBOX controllers, Compared to the streaming effects of moonlight, it's a piece of shit, and you don't have to care about it

The problem of the controller has been bothering me for a long time! I hope I can help you

**Comment by cgutman** [comment] 2017-11-27 05:30
Duplicate of https://github.com/moonlight-stream/moonlight-docs/issues/70

**Closed by cgutman** 2017-11-27 05:30 UTC
