### ISSUE TITLE
A/V data processing too slowly.

### ISSUE THREAD

**Issue by Xnome** [moonlight-stream/moonlight-android#316] opened 2016-12-24 20:14 UTC
I have been using Moonlight for quite a while and it used to work just fine, buy recently it has been giving me this error every single time no matter what the resolution and bit rate I choose. 

I tried moonlight on my iPhone and it seemed to work better, at least did not give me this error, however, there were some stuttering, but I guess because I was playing witcher 3 maxed out so maybe that's why.

I have recently upgraded from GTX 650 to 1070 could the bump in the Graphics be a problem? I can't seem to find a solution to this, tried various DNS server's on my internet. my router is 5 Ghz. Nvidia version is 3.2.096 and moonlight is the latest. 

If I may know what exactly causes this problem? its the internet speed I assume? any help would be greatly appreciated. Thank you!

**Comment by Xnome** [comment] 2016-12-30 15:38
I hope somebody can help me on this. it has become literally unplayable now.

**Comment by cgutman** [comment] 2016-12-30 16:49
What device are you seeing this issue on?

**Comment by Xnome** [comment] 2016-12-30 18:09
Okay so i have seem to have resolved this. It looks like the issue was H.265 (if stable) the moment i switched to do not use h.264 at all. it started working flawlessly. 0 stutter even on max settings with 100 bitrate. 

I do not understand, though, why suddenly this problem. I used to use the recommended settings i.e. use h.265 (if stable)

The device i have been seeing this problem is my Sony Android Tv. KDL55280C. i am okay with h.264 as long as i can play no max settings without any problem. it is weird though.

**Comment by cgutman** [comment] 2016-12-30 18:31
So that explains why you only see the issue now. Your GTX 650 was not able to send H.265 video, so it always used H.264.

Can you point me to a link to your TV model? Googling for "KDL55280C" returns nothing. I'd like to figure out what processor is in your TV so I can blacklist it for H.265.

**Comment by Xnome** [comment] 2016-12-31 03:32
Sorry. I typed wrong. Its KDL55W800C

here is the link: https://www.amazon.com/Sony-KDL55W800C-55-Inch-1080p-Smart/dp/B00R45XC0Y.

So if i am correct, then there cannot be any way of getting h.264, correct?

**Comment by cgutman** [comment] 2017-01-03 02:48
@Xnome Can you install the "AIDA64" app on your TV and upload pictures/screenshots of the CPU and Codecs tabs?

**Comment by Zocker1999NET** [comment] 2017-01-04 16:12
Have the same issue on my Sony KD-55x8005c, but only with low values for the bitrate (lower than 35). With higher values, it works but with an high latency (up to 100ms which makes nearly every game unplayable).

I think the new version of GeForce Experience tries to select the best bitrate automatically (because with a bitrate of 30, for me the main menu of Rocket League works perfectly but in a game, moonlight shows this issue and it stopped working) and if this bitrate exceeds the expected bitrate of Moonlight, Moonlight thinks the decoder of the device is too slow.

Maybe this high latency is a result of using a bad Wifi connection. In the near future, I will try it with a wired connection and report my results here.

**Comment by lHumaNl** [comment] 2017-01-29 10:57
I have the same problem on my Sony KDL43w808c. h264 works fine, but lattensy ~25-30. On h265 my tv rendering only the first frame of video, but audio streaming ok. Meanwhile, i download sample of h265/hevc 1080p video and play it on default sony player and playing starts normaly without any trouble. I think, the problem becouse moonlight doesn't see hevc codec of MTK SoC (mt5890) and use software codec from Google.

**Comment by lHumaNl** [comment] 2017-01-29 17:57
Here the link for codec tabs https://drive.google.com/file/d/0BxBKvhwh_5LAeXdsaF9iX2tlVDA/view?usp=drivesdk

**Comment by cgutman** [comment] 2017-01-29 18:28
@lHumaNl so you had to manually force H.265 enabled in Moonlight settings for it to hit this issue?

**Comment by lHumaNl** [comment] 2017-01-30 04:27
Yeap. On h265 my tv rendering only the first frame of video, but audio streaming ok.

**Comment by Zocker1999NET** [comment] 2017-01-30 06:48
On my TV the same too. Only the first frame will be rendered.

**Comment by diehardguy** [comment] 2017-04-21 00:15
What is the reason for this? I have a Philips Android tv that works fine but the Sony stutters like hell, both using wired connections to the desktop. The Sony has better chipset. What is the fix @cgutman

**Comment by diehardguy** [comment] 2017-04-21 12:05
I have a KD-49XD8008 which apparently has hevc support, the stream appears to work on Moonlight but extremely laggy and choppy.  I also have a Philips 49pus6401 and 32pfs5501 which both have no issues with moonlight and both have inferior cpu. Only thing I see is the Sony is 64bit Android.  I used AIDA64 and the codecs look same, can see h.264 there on both

**Comment by Xnome** [comment] 2017-04-21 12:07
The problem is using h.265 (i don't remember the number correctly, but
whatever is the recommended one) use the lower one and it should work just
fine.

**Comment by diehardguy** [comment] 2017-04-21 12:17
How do you select the lower version?  In moonlight?  When I select never use h.265 I still have the same issue. If I drop off the session on the Sony and reopen on the Philips, no problems at all and h.265 is set to use h.265 if stable on the Philips.

Sent from my iPhone

On 21 Apr 2017, at 13:07, Xnome <notifications@github.com<mailto:notifications@github.com>> wrote:

The problem is using h.265 (i don't remember the number correctly, but
whatever is the recommended one) use the lower one and it should work just
fine.

**Comment by diehardguy** [comment] 2017-04-21 12:25
Ok so selecting always use h.265 in moonlight works fine? Why?

**Comment by diehardguy** [comment] 2017-04-21 12:26
Also @cgutman and Xbox app plans?

**Comment by diehardguy** [comment] 2017-04-21 12:35
Spoke too soon, using at anything over 720p 60fps causes extreme stuttering in the Sony. On the Philips I can use 4k setting with a little lag. Is it tee case that the Sony is just crap?  Surely it must be ok given Playstation now is installed.  This is a deal breaker for me on this tv will have to go back......

**Comment by Xnome** [comment] 2017-04-21 12:46
It works for me if I force h.265 or 264 (i am not in front of my computer
so i don't know which is the lower one) I think it has something to do with
sony not supporting that Codec. you must be having some other issue then?

**Comment by diehardguy** [comment] 2017-04-21 12:56
Was your tv 32 bit?  Is moonlight optimised for 64bit Android?

**Comment by lHumaNl** [comment] 2017-04-22 10:34
A one week ago, my TV Sony kdl43w808c get the update Android to version 6.0.1. After that Moonlight starts streaming on h265 codec, but max resolution where the stream works fine is 720p60. On 1080p30 or 1080p60 my tv still rendering only the first frame of video.

**Comment by diehardguy** [comment] 2017-04-22 11:17
Ok makes sense as my Philips TVs are 5.2 and 6.0. So what has changed? Is this a moonlight specific issue or android issue?  I'll be willing to make any code changes.

**Comment by diehardguy** [comment] 2017-04-22 11:34
Scratch that the Philips is also on 6.0.1. So what is the delta from the previous build on Sony before 6.0.1. I have the same issue on 60fps. Note if I disconnect the session from Sony and continue on the Philips tv I can stream at 4k 60fps. I am using power line adapters on all my devices to have high bandwidth.

**Comment by yostyle** [comment] 2017-12-08 13:50
On my 49PUS6401 Philips TV with android 7 I enable MTK codec in source code. It works great !

**Comment by cgutman** [comment] 2017-12-08 17:34
Yep, this is fixed in Moonlight v5.6.1. Make sure GeForce Experience is at least at v3.11 too.

You shouldn't need to change any source, just set Moonlight to always use H.265 in the settings.

**Closed by cgutman** 2017-12-08 17:34 UTC

**Comment by 90Ninety** [comment] 2018-03-20 23:15
I have this same issue with Sony Bravia with Android KD-49X8307C . first frame is rendered , then a garbled mess . I have tried every video option including forcing H264 encoding , this makes no difference . I have gigabit cabling around the house and I steam from PC with 1080ti .  On the same network my Huawei P10 lite works perfect . Any other suggestion ?
