### ISSUE TITLE
USB mouse and Bluetooth Keyboard Issues.

### ISSUE THREAD

**Issue by squiffzor** [moonlight-stream/moonlight-android#140] opened 2016-01-05 23:28 UTC
So I rooted my Tab S2 because it wanted to use a mouse among keyboard to stream Wow through nvidia GE. All works good and well untill I launch Wow from the games list. I get the nvidia gamestream just before the wow login screen and lose all mouse and keyboard function. If i unplug the mouse and reconnect it, i get it back but with that annoying double cursor and screen edge problem. The keyboard and mouse function on my pc so its not a program crash. I am using SuperSU Pro root management. This is the same for all games and the steam dash too. I am using the newest moonlight rooted from the play store.

Any help would be appreciated...

**Comment by cgutman** [comment] 2016-01-06 00:23
OK, in settings go to Developer Options (if you don't have Developer Options, go to About then tap Build number until it says you're a developer). Go ahead and start Moonlight with your mouse and keyboard plugged in, then unplug and replug your keyboard and mouse, then go back to Developer Options and tap Take Bugreport. Save the bugreport to your Google Drive and put a link here.

**Comment by cgutman** [comment] 2016-01-06 19:11
Actually can you try this APK and tell me if it fixes your issue? https://onedrive.live.com/redir?resid=C15BF9770619F56!160684&authkey=!AKt5pu5UxMkx9G0&ithint=file%2capk

**Comment by squiffzor** [comment] 2016-01-06 20:49
Thanks for getting back to me so quickly.
So i uninstalled Moonlight and replaced it with the APK and it still does the same thing. Works untill i try to play a game i lose the USB mouse and Bluetooth KB. When i reconnect the mouse i get the double mouse cursor and invisible window edge. Anyway, here is the bug report you requested.

Thanks.
[bugreport.txt](https://github.com/moonlight-stream/moonlight-android/files/80342/bugreport.txt)
![bugreport-2](https://cloud.githubusercontent.com/assets/16566916/12154367/f4702d66-b4b6-11e5-95b7-74d66f941ef0.png)

**Comment by cgutman** [comment] 2016-01-06 23:23
OK, thanks for the report. I added a bunch more debug messages to a new version. Please take another bug report with this APK: https://onedrive.live.com/redir?resid=C15BF9770619F56!160686&authkey=!ALro_rJnqUl0ywk&ithint=file%2capk

**Comment by cgutman** [comment] 2016-01-07 05:42
I've tried on several of my devices and haven't been able to reproduce the issue:
- Nvidia Shield Portable with 5.1.1 (rooted with SuperSU 2.46 ZIP)
- Nexus 7 2013 - Stock 6.0.1 rooted with SuperSU 2.66 ZIP and Cyanogenmod 13.0 Nightly
- Nexus 9 - Stock 6.0.1 rooted with SuperSU 2.66 ZIP
- HP Touchpad - Cyanogenmod 11
- Galaxy Nexus - Cyanogenmod 13

On all devices, I confirmed that it was working with a USB OTG mouse (except Touchpad) and Bluetooth mouse.

**Comment by squiffzor** [comment] 2016-01-07 07:11
I wonder if it could be due to my mouse being a gaming mouse. It has a built in Dpi adjuster and uses software to control it. I will try a generic pnp mouse later. The unrooted version seems to work except for the double mouse and invisible window problem. Thanks for trying to sort it anyway. Looks like i will just have to get a gaming laptop instead 😁

**Comment by cgutman** [comment] 2016-01-07 07:16
I still think there's a bug in my code though. Especially since it doesn't regrab the input devices when you re-plug them (and it never even seems to know that they're gone). That seems to indicate that the polling threads are hung. Getting that bug report with my extra debugging APK should tell me where the polling threads are hanging.

**Comment by squiffzor** [comment] 2016-01-07 10:42
Ran the new APK with a different (generic mouse) No luck, not that i thought there would be.... but here is the bug report from the new APK
[bugreport.txt](https://github.com/moonlight-stream/moonlight-android/files/80990/bugreport.txt)

**Comment by cgutman** [comment] 2016-01-07 18:51
OK, that bug report was quite useful. I'm almost certain I fixed it this time. Try this APK: https://onedrive.live.com/redir?resid=C15BF9770619F56!160687&authkey=!AHozMH8LLx3A64E&ithint=file%2capk

**Comment by squiffzor** [comment] 2016-01-07 21:54
Legend! Fixed it! Thanks for being so helpful! Hopefully anyone else who runs into issues can sort it using this thread. It all works awesomely 😁😁

**Comment by cgutman** [comment] 2016-01-08 00:19
The fix is released in v4.0.4,

**Closed by cgutman** 2016-01-08 00:19 UTC
