### ISSUE TITLE
Mouse capture not working in windows 10 DeX (Android 10) 

### ISSUE THREAD

**Issue by Miyoujin** [moonlight-stream/moonlight-android#789] opened 2020-02-03 10:25 UTC
I have the Samsung S10 with android 10, when i'm using moonlight on windows 10 samsung DeX it works as normal but the mouse doesn't move. Left click and right click and other feature works perfectly but the mouse don't move.

**Comment by Zanathoz** [comment] 2020-02-26 14:58
I can verify this is a bug with Moonlight. 

My Note 9 will pass mouse control over to Moonlight when using the DeX dock, but will not pass mouse control over when using DeX for PC. The mouse control remains in the DeX, although right and left mouse clicks are passed properly to my desktop as Miyoujin mentions in his post.

**Comment by cgutman** [comment] 2020-02-26 19:07
I think this is just because DeX for Windows doesn't support the Android pointer capture API. They would need to support that specifically to make Moonlight's pointer capture work.

Is there any other game/app that has working mouse capture in DeX for Windows? Notably, this means the mouse is actually captured in the DeX window, not just hidden or whatever.

**Comment by Zanathoz** [comment] 2020-03-02 18:34
I just tested Splashtop Remote Desktop on DeX for PC and mouse capture is working correctly with it.

**Comment by cgutman** [comment] 2020-03-03 08:55
Does the mouse cursor remain trapped in the Splashtop window or does it move freely out of the window?

**Comment by Zanathoz** [comment] 2020-03-09 11:44
I don't have my laptop to test at the moment, but I recall the DeX cursor remained over-top of the Splashtop cursor while interacting with the desktop. I did forget to mention that, so it's not fully captured as you mentioned previously but more of an overlay.

**Comment by cgutman** [comment] 2020-04-18 07:12
I confirmed it works as I had guessed - without support for mouse capture.

Fortunately, Nvidia has implemented absolute mouse motion in a recent update of their official client and I was able to reverse engineer the input protocol to make it work.

This is fixed in https://github.com/moonlight-stream/moonlight-android/commit/c3b81554f43301a7e37a1d6bf743df9ff3f3ae0f confirmed on my Note 9.

**Closed by cgutman** 2020-04-18 07:12 UTC
